### ISSUE TITLE
Nexus Info tab problem

### ISSUE THREAD

**Issue by HiT333** [ModOrganizer2/mob#84]
Sorry for my English. When I click on the Nexus Info tab (in mod information) my computer freezes, the screen starts to turn off and on. The task manager cannot be called. I have to reload via reset. The same thing happens when I press the button to sort plugins using LOOT (above the list of mods). If I run LOOT without MO there is no problem. There was nothing like this with other programs / games. I use MO for Skyrim LE, Fallout3 and NV.
Windows 7 SP1 64bit system. Videocard Asus HD7750.

**Comment by isanae** [comment]
This sounds like a problem with your graphics card or drivers. Both the Nexus tab and the Sort window use an integrated web browser based on Chrome, which uses hardware acceleration.

**Comment by isanae** [comment]
I'm closing this for now because 1) I doubt it's related to MO, and 2) it's in the wrong place, issues should be opened on [the MO repo](https://github.com/ModOrganizer2/modorganizer/issues).
